### ISSUE TITLE
Consider Fuchsia platform

### ISSUE THREAD

**Issue by hundeva** [fuzz-productions/platty#1]
Even though it is extremely early, and not exactly testable, the logic on choosing between material and cupertino is a bit flawed [here](https://github.com/fuzz-productions/platty/blob/master/lib/widgets/platform.dart#L20).

Consider something like this instead:

```dart
    return platform == TargetPlatform.ios
        ? renderCupertino(context)
        : renderMaterial(context);
```

This way, Cupertino will be applied on iOS only, as it should be. The original logic would place Fuchsia in the Cupertino bucket as well.

**Comment by Cliabhach** [comment]
So....you're suggesting we use Material by default? I suppose that might work.

**Comment by hundeva** [comment]
Well, I think Flutter is primarily a Material based framework, which starts to gain better Cupertino support. Also, Fuchsia is probably going to be Material based as well, so it only makes sense to me to have Material as default.

**Comment by agrosner** [comment]
Now we utilize a switch on the target:
```
final platform = this.renderPlatform ?? PTheme.of(context).data.platform;
    switch (platform) {
      case TargetPlatform.android:
        return renderMaterial(context);
      case TargetPlatform.iOS:
        return renderCupertino(context);
      case TargetPlatform.fuchsia:
        return renderFuchsia(context);
```
where `renderFuschia` points to `renderMaterial`, but still allows you to define custom implementation if need be.
